coverage:
  status:
    project:
      default:
        target: 80%
    patch:
      default:
        target: 90%
ignore:
    - "QuickCal/Previews"
    - "QuickCal/Persistence.swift"
    - "QuickCalTests"
    - "QuickCalUITests"
