coverage:
  status:
    project:
      default:
        target: 95%
    patch:
      default:
        target: 100%
ignore:
    - "QuickCal/Previews"
    - "QuickCal/Persistence.swift"
    - "QuickCalTests"
    - "QuickCalUITests"
