name: Codecov

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-12
    steps:
      - name: Checkout Codecov
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project QuickCal.xcodeproj -scheme QuickCal -destination 'platform=iOS Simulator,name=iPhone 11,OS=15.5' -enableCodeCoverage YES build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
